allowLineBreaksInTitles: false
color: orange
description: null
fieldLayouts:
  12cb2539-8e3b-4fad-a3b4-d80911d25c7d:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:3193fdca-69c1-45c2-a6df-97b4080f10ee'
      - 'layoutElement:29c710ac-2bf6-4161-b059-5d3c3011a058'
      - 'layoutElement:b3a8c432-0685-4a20-9004-42c741d6af7e'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-03-16T16:55:57+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 394137d7-b17b-4bf5-9bc2-62dcc5d06808 # Plain Text
            handle: heading
            instructions: null
            label: Überschrift
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3193fdca-69c1-45c2-a6df-97b4080f10ee
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-16T16:55:57+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 394137d7-b17b-4bf5-9bc2-62dcc5d06808 # Plain Text
            handle: subtilte
            instructions: null
            label: Untertitel
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 29c710ac-2bf6-4161-b059-5d3c3011a058
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-16T16:55:57+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 983f3c7c-a082-4298-bd61-06d175c7cba8 # Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3a8c432-0685-4a20-9004-42c741d6af7e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-16T16:55:57+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7d5cf96b-6d4e-4c4b-b9c4-02591bfa3bbd # FAQ-Items
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ef14841-65e4-4012-87b9-0489b0161787
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 52967e35-8fd4-407e-b3f6-5da4415b5266
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-03-16T17:02:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6c9288d8-5d14-4d35-b4be-c9cfe19a18bc # Hintergrundfarbe
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e9ac672-e26e-409c-a108-981ef76eb770
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-16T17:02:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 89d9744a-dbc1-4b8a-ac14-bcb5f9ca1d9b # Textausrichtung
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad99e634-dc35-4b28-99d3-fe60d58ec0f6
            userCondition: null
            warning: null
            width: 100
        name: Einstellungen
        uid: d1d1f97f-7966-476e-b0dc-e6b850ddb401
        userCondition: null
    thumbFieldKey: null
handle: faqSection
hasTitleField: false
icon: comments-question
name: FAQ
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
