allowLineBreaksInTitles: false
color: orange
description: null
fieldLayouts:
  a465adc0-6a7e-4357-99c7-c12c8d644f80:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-03-16T17:00:58+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 983f3c7c-a082-4298-bd61-06d175c7cba8 # Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43653d1c-e4e3-411e-a957-1dd58c698fd6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-16T17:00:58+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 394137d7-b17b-4bf5-9bc2-62dcc5d06808 # Plain Text
            handle: quoteAuthor
            instructions: null
            label: Autor
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72b00123-5cd3-41c3-bf6b-c764e9f3bd9e
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 0b4e2698-4007-414a-b818-e8d40c77f884
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-03-16T17:00:58+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6c9288d8-5d14-4d35-b4be-c9cfe19a18bc # Hintergrundfarbe
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9fad204-61ef-4f8e-b358-548b0b2b9d8c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-16T17:00:58+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d35cbd98-b3a8-42a9-acfd-c9c53d0f60a6 # Highlight-Typ
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1269b759-0ad0-4b41-b1a2-119e5c2462b6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-16T17:00:58+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4111023a-b9d2-4eb9-9d57-5638426d40a4 # Icon zeigen
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6dc7c019-9f72-4102-9b1c-f62853563c48
            userCondition: null
            warning: null
            width: 100
        name: Einstellungen
        uid: 23081576-67cf-446f-b221-17f0d8abdcc4
        userCondition: null
    thumbFieldKey: null
handle: highlightBox
hasTitleField: false
icon: star
name: 'Highlight Box / Pullquote'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
